class Constants:
    value_dict = {
        "casa": "Casa",
        "machamba": "Machamba",
        "principal": "Principal",
        "alternativo": "Alternativo",
        "deslocada": "Deslocada",
        "acolhedora": "Acolhedora",
        "bi": "BI",
        "nuit": "NUIT",
        "cartao_eleitor": "Cartao de eleitor",
        "certidao_nascimento": "Certidao de Nascimento",
        "cedula": "Cedula Pessoal",
        "nao_tem": "Nao tem Documento",
        "outro": "Outro",
        "masculino": "Masculino",
        "feminino": "Feminino",
        "sim": "Sim",
        "sem_renda_com_membros_capaz_trabalhar": "Sem renda, com membros capazes de trabalhar",
        "fam_desloc_chefiadas_menor": "Familias deslocadas chefiadas por menor",
        "fam_com_crianc_desnutridas": "Familias com criancas desnutrida",
        "fam_situacao_pobreza_vulnerabdade": "Familias em situacao de pobreza e vulnerabilidade",
        "fam_chef_mulher": "Familia chefiada por mulher",
        "fam_com_deficiencia": "Familia com deficiente, doente cronico, idoso",
        "nampula": "Nampula",
        "cabo_delgado": "Cabo Delgado",
        "nacoroa": "Nacoroa",
        "nampula": "Nampula",
        "meconta": "Meconta",
        "erati": "Erati",
        "chiure": "Chiure",
        "montepuez": "Montepuez",
        "balama": "Balama",
        "namuno": "Namuno",
        "ancuabe": "Ancuabe",
        "metuge": "Metuge",
        "vila_montepuz": "Vila de Montepuez",
        "mirate": "Mirate",
        "impiri": "Impiri",
        "namuno_sede": "Namuno-Sede",
        "meza": "Meza",
        "metouro": "Metouro",
        "metuge_sede": "Metuge-Sede",
        "mieze": "Mieze",
        "chiure_sede": "Chiure-Sede",
        "chiure_velho": "Chiure-velho",
        "katapua": "Katapua",
        "nacoroa_sede": "Nacoroa-Sede",
        "anchilo": "Anchilo",
        "corrane": "Anchilo",
        "alua": "Alua",
        "namapa": "Namapa",
        "montepuez": "Montepuez",
        "mirate_sede": "Mirate-Sede",
        "marrarange": "Marrarange",
        "sivaca": "Sivaca",
        "milipone": "Milipone",
        "nanjua": "Nanjua",
        "salaue": "Salaue",
        "nacuta": "Nacuta",
        "metuge_sede": "Metuge-Sede",
        "nanlia": "Nanlia",
        "mieze_sede": "Mieze-Sede",
        "jonga": "Jonga",
        "localidade_sede": "Localidade-Sede",
        "katapua_sede": "Katapua-Sede",
        "meculane": "Meculane",
        "mocotia": "Mocotia",
        "saua_saua": "Saua-Saua",
        "namiconha": "Namiconha",
        "namachilo": "Namachilo",
        "anchilo_sede": "Anchilo-Sede",
        "corrane_sede": "Corrane-Sede",
        "alua_sede": "Alua-Sede",
        "namapa_sede": "Namapa-Sede",
        "nicuapa": "Nicuapa",
        "mirate_sede": "Mirate-Sede",
        "marrarange": "Marrarange",
        "impiri_sede": "Impiri-Sede",
        "nquiriquele": "Nquiriquele",
        "nanjua_a": "Nanjua A",
        "nanjua_b": "Nanjua B",
        "marocane": "Marocane",
        "nankomi": "Nankomi",
        "pulo": "Pulo",
        "unidade": "Unidade",
        "cuaia": "Cuaia",
        "ngalane": "Ngalane",
        "ntocota": "Ntocota",
        "ngunga": "Ngunga",
        "naminaue": "Naminaue",
        "marrupa": "Marrupa",
        "nrehili": "Nrehili",
        "katapua_sede": "Katapua-Sede",
        "tutua": "Tutua",
        "meculane": "Meculane",
        "mavalane": "Mavalane",
        "mucova": "Mucova",
        "thapula": "Thapula",
        "muhavula": "Muhavula",
        "kalima": "Kalima",
        "moloa": "Moloa",
        "mucupassa": "Mucupassa",
        "ampivine": "Ampivine",
        "tanhea": "Tanhea",
        "nacuculo": "Nacuculo",
        "cathaia": "Cathaia",
        "nanhaca": "Nanhaca",
        "emprestada": "Emprestada",
        "alugada": "Alugada",
        "outra": "Outra",
        "comprou": "Comprou",
        "alugada": "Alugada",
        "cedido_pelo_lider": "Cedido Pelo Lider",
        "cedido_pelo_governo": "Cedido Pelo Governo",
        "antes_ primeiro_sem_ 2019": "Antes do primeiro semestre de 2019",
        "primeiro_sem_2019": "Primeiro semestre de 2019",
        "segundo_sem_2019": "Segundo semestre de 2019",
        "primeiro_sem_2020": "Primeiro semestre de 2020",
        "segundo_sem_2020": "Segundo semestre 2020",
        "primeiro_sem_2021": "Primeiro semestre 2021",
        "segundo_sem_2021": "Segundo semestre de 2021",
        "primeiro_sem_2022": "Primeiro semestre de 2022",
        "zona_alta": "Zona alta",
        "zona_baixa": "Zona baixa",
        "pantano": "Pantano",
        "sim": "Sim",
        "nao": "Nao",
        "arenoso": "Arenoso",
        "argiloso": "Argiloso",
        "areno_argiloso": "Areno Argiloso",
        "preto": "Preto",
        "castanho": "Castanho",
        "em_uso": "Em Uso",
        "em_pousio": "Em Pousio",
        "virgem": "Virgem",
        "menor_or_igual_15_minutos": "Menor ou igual a 15 Minutos",
        "15_a_45_minutos": "15 a 45 Minutos",
        "45_min_a_1_hora": "45 Minutos a 1 hora",
        "mais_que_1_hora": "Mais que 1 hora",
        "antes_das_chuvas": "Antes das Chuvas",
        "depois_das_chuvas": "Depois das Chuvas",
        "semente_pre_basica": "Semente pre-basica",
        "semente_basica": "Semente basica",
        "semente_1_geracao": "Semente certificada de 1 gearacao",
        "semente_2_geracao": "Semente certificada de 2 geracao",
        "semente_melhorada": "Semente garantida melhorada",
        "a": "Kit A",
        "b": "Kit B",
        "c": "Kit C",
        "d": "Kit D",
        "confirma": "Confirma",
        "nao_confirma": "Nao confirma",
        "fornecedor": "Fornecedor",
        "extensionista": "Extensionista",
        "beneficiario": "Beneficiario",
        "antes_das_chuvas": "Antes das Chuvas",
        "durante_queda_das_chuvas": "Durante a queda das Chuvas",
        "depois_queda_das_chuvas": "Depois da queda das Chuvas",
        "feijao_manteiga": "Feijao Manteiga",
        "feijao_nhemba": "Feijao Nhemba",
        "feijao_boer": "Feijao Boer",
        "amendoim": "Amendoim",
        "milho": "Milho",
        "0_5_dias": "0-5 dias",
        "5_10_dias": "5-10 dias",
        "10_15_dias": "10-15 dias",
        "acima_15_dias": "Acima de 15 dias",
        "toda_area_plantada": "Toda area plantada",
        "mais_metade_area_plantada": "Mais da Metade da area plantada",
        "menos_metade_area_plantada": "Menos da metade da area plantada",
        "nao_germinou": "Nao germinou nada",
        "npk": "NPK",
        "antes_sementeira": "Antes da sementeira",
        "depois_sementeira": "Depois da sementeira",
        "antes_germinacao": "Antes da germinacao",
        "depois_germinacao": "Depois da germinacao",
        "machamba_beneficiario": "Machamba do beneficiario",
        "campo_demonstracao": "Campo de demonstracao",
        "sede_bairro": "Sede bairro",
        "durante_sacha": "Durante sacha",
        "recebeu": "Recebeu",
        "nao_recebeu": "Nao recebeu",
        "preparacao_solos": "Preparacao Solos",
        "sementeira": "Sementeira",
        "sacha": "Sacha",
        "adubacao": "Adubacao",
        "combate_pragas_doencas": "Combate a pragas e doencas",
        "colheita": "Colheita",
        "conservacao": "Conservacao",
        "lead_farmer": "Lead Farmer",
        "durante_preparacao_terra": "Durante preparacao da terra",
        "durante_sementeira": "Durante sementeira",
        "alocacao_terra": "ALocacao da terra",
        "nao_quer_falar": "Nao quer falar",
        "lider_comunitario": "Lider comunitario",
        "chefe_posto": "Chefe do posto",
        "secretario_bairro": "Secretario do bairro",
        "regulo": "Regulo",
        "lider_religioso": "Lider religioso",
        "policia": "Policia",
        "violencia_fisica": "Violencia Fisica",
        "violencia_sexual": "Violencia Sexual",
        "assedio_sexual": "Assedio Sexual",
        "exploracao_e_abuso_sexual": "Exploracao e abuso Sexual",
        "uma_semana": "Uma Semana",
        "duas_semanas": "Duas Semanas",
        "tres_semanas": "Tres Semanas",
        "mais_que_tres_semanas": "Mais do que 3 semanas",
        "0.5": "0.5 ha",
        "1.5": "1.5 ha",
        "bom_estado": "Bom estado",
        "razoavel": "Razoavel",
        "podres_mau": "Podres/mau"

    }

    numeros_dict = {
        "1": " Nome da espécie e variedade",
        "2": "Número ou outra identificação do lote",
        "3": "Peso líquido",
        "4": "Data de embalagem",
        "5": "Nome da empresa produtora ou embaladora",
        "6": "Prazo de validade do teste de germinação",
        "7": "País de origem",
        "8": "Número de sementes",
        "9": "Percentagem de germinação",
        "10": "Percentagem de pureza",
        "11": "Percentagem de humidade",
        "12": "Limitação de garantia",
        "13": "Tipo de tratamento",
        "14": "Nome do produto utilizado",
        "15": "Advertência caso o produto seja prejudicial a saúde humana",
        "16": "Etiquetas brancas cruzadas com barra azul",
        "17": "Etiquetas brancas cruzadas com uma barra vermelha",
        "18":  "Etiqueta amarela",
        "19":  "Etiqueta azul",
        "sim": "Sim",
        "nao": "Nao",
        "'1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12": "Embalagens tem todo tipo de informacao",
        "'13, 14, 15": "As sementes foram tratadas com algum produto químico e a embalagem apresenta todas informacoes",
        "'16, 17, 18": "As etiquetas estão classificadas de todas formas"

    }

    def get_dicionario(self):
        return self.value_dict

    def get_numeros(self):
        return self.numeros_dict
