from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', views.home, name='home'),
    path('push_data', views.push_data, name='push_data'),
    path('relatorio_posse_machamba', views.relatorio_posse_machamba,
         name='relatorio_posse_machamba'),
    path('relatorio_machamba_pertenca', views.relatorio_machamba_pertenca,
         name='relatorio_machamba_pertenca'),
    path('relatorio_tipo_posse', views.relatorio_tipo_posse,
         name='relatorio_tipo_posse'),
    path('relatorio_forma_aquisicao', views.relatorio_forma_aquisicao,
         name='relatorio_forma_aquisicao'),
    path('relatorio_quando_teve_machamba', views.relatorio_quando_teve_machamba,
         name='relatorio_quando_teve_machamba'),
    path('relatorio_tamanho_machamba', views.relatorio_tamanho_machamba,
         name='relatorio_tamanho_machamba'),
    path('relatorio_local_machamba', views.relatorio_local_machamba,
         name='relatorio_local_machamba'),
    path('relatorio_caracteristica_solos', views.relatorio_caracteristica_solos,
         name='relatorio_caracteristica_solos'),
    path('relatorio_cor_solo', views.relatorio_cor_solo, name='relatorio_cor_solo'),
    path('relatorio_historico_uso_solo', views.relatorio_historico_uso_solo,
         name='relatorio_historico_uso_solo'),
    path('relatorio_quando_recebeu', views.relatorio_quando_recebeu,
         name='relatorio_quando_recebeu'),
    path('relatorio_recebeu_semente', views.relatorio_recebeu_semente,
         name='relatorio_recebeu_semente'),
    path('relatorio_tipo_kit', views.relatorio_tipo_kit, name='relatorio_tipo_kit'),
    path('relatorio_de_quem_recebeu_semente', views.relatorio_de_quem_recebeu_semente,
         name='relatorio_de_quem_recebeu_semente'),
    path('relatorio_tipo_familia', views.relatorio_tipo_familia,
         name='relatorio_tipo_familia'),
    path('relatorio_genero', views.relatorio_genero, name='relatorio_genero'),
    path('relatorio_elegibilidade', views.relatorio_elegibilidade,
         name='relatorio_elegibilidade'),
    path('relatorio_comunidade', views.relatorio_comunidade,
         name='relatorio_comunidade'),
    path('relatorio_quando_realizou_sementeira', views.relatorio_quando_realizou_sementeira,
         name='relatorio_quando_realizou_sementeira'),
    path('relatorio_sementes_germinou', views.relatorio_sementes_germinou,
         name='relatorio_sementes_germinou'),
    path('relatorio_semente_nao_germinou', views.relatorio_semente_nao_germinou,
         name='relatorio_semente_nao_germinou'),
    path('relatorio_canais_reclamacao', views.relatorio_canais_reclamacao,
         name='relatorio_canais_reclamacao'),
    path('relatorio_apresentou_reclamacao', views.relatorio_apresentou_reclamacao,
         name='relatorio_apresentou_reclamacao'),
    path('relatorio_canal_usado', views.relatorio_canal_usado,
         name='relatorio_canal_usado'),
    path('relatorio_tempo_gasto_resolver', views.relatorio_tempo_gasto_resolver,
         name='relatorio_tempo_gasto_resolver'),
    path('relatorio_ficou_satisfeito', views.relatorio_ficou_satisfeito,
         name='relatorio_ficou_satisfeito'),
    path('relatorio_ja_ouviu_vbg', views.relatorio_ja_ouviu_vbg,
         name='relatorio_ja_ouviu_vbg'),
    path('relatorio_vitima_vbg', views.relatorio_vitima_vbg,
         name='relatorio_vitima_vbg'),
    path('relatorio_canais_denunciar', views.relatorio_canais_denunciar,
         name='relatorio_canais_denunciar'),
    path('relatorio_teve_toda_assistencia', views.relatorio_teve_toda_assistencia,
         name='relatorio_teve_toda_assistencia'),
    path('relatorio_tipo_vbg', views.relatorio_tipo_vbg, name='relatorio_tipo_vbg'),
]
