# Generated by Django 4.0.2 on 2022-03-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoareagerminacao',
            name='sementeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sementeira'),
        ),
        migrations.AlterField(
            model_name='tiposementegerminou',
            name='sementeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sementeira'),
        ),
    ]
